apiVersion: v1
data:
  nginx.conf: "user nginx;\nworker_processes  3;\nerror_log  /var/log/nginx/error.log;\nevents
    {\n  worker_connections  10240;\n}\nhttp {\n  log_format  main\n          'remote_addr:$remote_addr\\t'\n
    \         'time_local:$time_local\\t'\n          'method:$request_method\\t'\n
    \         'uri:$request_uri\\t'\n          'host:$host\\t'\n          'status:$status\\t'\n
    \         'bytes_sent:$body_bytes_sent\\t'\n          'referer:$http_referer\\t'\n
    \         'useragent:$http_user_agent\\t'\n          'forwardedfor:$http_x_forwarded_for\\t'\n
    \         'request_time:$request_time';\n\n  access_log\t/var/log/nginx/access.log
    main;\n\n  server {\n      listen       80;\n      server_name  _;\n\n      location
    / {\n          root   html;\n          index  index.html index.htm;\n      }\n
    \ }\n  include /etc/nginx/virtualhost/virtualhost.conf;\n}\n"
  virtualhost.conf: |
    upstream app {
      server localhost:8080;
      keepalive 1024;
    }

    server {
      listen 8000 default_server;
      root /usr/local/app;

      access_log /var/log/nginx/app.access_log main;
      error_log /var/log/nginx/app.error_log;

      location / {
        proxy_pass http://app/;
        proxy_http_version 1.1;
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"nginx.conf":"user nginx;\nworker_processes  3;\nerror_log  /var/log/nginx/error.log;\nevents {\n  worker_connections  10240;\n}\nhttp {\n  log_format  main\n          'remote_addr:$remote_addr\\t'\n          'time_local:$time_local\\t'\n          'method:$request_method\\t'\n          'uri:$request_uri\\t'\n          'host:$host\\t'\n          'status:$status\\t'\n          'bytes_sent:$body_bytes_sent\\t'\n          'referer:$http_referer\\t'\n          'useragent:$http_user_agent\\t'\n          'forwardedfor:$http_x_forwarded_for\\t'\n          'request_time:$request_time';\n\n  access_log\t/var/log/nginx/access.log main;\n\n  server {\n      listen       80;\n      server_name  _;\n\n      location / {\n          root   html;\n          index  index.html index.htm;\n      }\n  }\n  include /etc/nginx/virtualhost/virtualhost.conf;\n}\n","virtualhost.conf":"upstream app {\n  server localhost:8080;\n  keepalive 1024;\n}\n\nserver {\n  listen 80 default_server;\n  root /usr/local/app;\n\n  access_log /var/log/nginx/app.access_log main;\n  error_log /var/log/nginx/app.error_log;\n\n  location / {\n    proxy_pass http://app/;\n    proxy_http_version 1.1;\n  }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"nginx-conf","namespace":"blue"}}
  creationTimestamp: "2022-08-31T14:21:36Z"
  name: nginx-conf
  namespace: blue
  resourceVersion: "66303"
  uid: 9ef528b2-4be3-4e40-8cbb-5004f4a37561
