[build]
 base = "/"
 publish = "client/dist"
 command = "bash client/build4netlify.sh"

[[plugins]]
 package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "packages/calc/eval"
